# Generated by Django 4.1.7 on 2023-03-03 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Moods',
            new_name='Mood',
        ),
    ]
