# Generated by Django 4.1.7 on 2023-03-06 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_mood_favorites_mood_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='genmood',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=250)),
                ('mood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.mood')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('mood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.mood')),
            ],
        ),
    ]
