# Generated by Django 4.1.7 on 2023-03-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_mood_genmood_song_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('thumbnail', models.URLField(max_length=500)),
                ('video_id', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='mood',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='moods', to='main_app.video'),
        ),
    ]
