# Generated by Django 4.1.7 on 2023-03-10 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_video_mood_videos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Song',
        ),
    ]
